# Generated by Django 2.2.5 on 2020-05-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200430_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Type'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='file_image',
            new_name='file',
        ),
    ]
